### PR TITLE
Fix/Rationalize transports (v2)

### LINKED ISSUE #91: DELETE does not allow POST-style data
One of our API calls using method DELETE requires JSON in a POST field. We had been doing it with straight cURL. When transitioning to Requests, I tried the delete method but that didn't allow data to be passed. Then, I attempted to just use the request method.

    $response = Requests::request($url, $headers, $data, Requests::DELETE, $options);

URL:

https://REMOVED/terminus.php?site=UUID&path=code-branch

headers:

````
Array (
    [Content-Type] => application/json
    [Content-Length] => 40
)
````

data:

    {"data":{"refspec":"refs\/heads\/prog"}}

method: DELETE

options:

````
Array (
    [timeout] => 30
    [cookies] => Array (
            [0] => REMOVED
        )
    [verifyname] => FALSE
    [verify] => FALSE
)
````

That caused:

    http_build_query(): Parameter 1 expected to be Array or Object. Incorrect value given cURL.php:327

https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/cURL.php#L327

I believe the problem is at:

https://github.com/rmccue/Requests/blob/022400b23f697792fa340c93d250257293c6ec37/library/Requests/Transport/cURL.php#L224

This assumes that DELETE won't be POSTing. Additionally:

https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/cURL.php#L241

cURL isn't setting options for CURLOPT_POST or CURLOPT_POSTFIELDS.

I'll admit that this is a bit edge-case. However, it doesn't seem to be against RFC. http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request gets into that in greater detail.

I have no problem setting an additional option or calling the request method in a different way.

Let me know if you have any questions or if you need more context! Thanks in advance.

### LINKED ISSUE #137: Support for OPTIONS http method
Could you please add support for OPTIONS http method. We are using this method for feature detection from one of our APIs.

### PR DESCRIPTION
**Pull request by rmccue**
Following on from @egeloen's fantastic work in #143, this merges master in and corrects some small issues.

Fixes #137, fixes #91.

### CODE REVIEW

File: library/Requests/Transport/cURL.php [hunk 1]
```diff
@@ -296,15 +311,18 @@ protected function setup_handle($url, $headers, $data, $options) {
...
+			case Requests::OPTIONS:
 				curl_setopt($this->handle, CURLOPT_CUSTOMREQUEST, $options['type']);
 				curl_setopt($this->handle, CURLOPT_POSTFIELDS, $data);
 				break;
-			case Requests::DELETE:
-				curl_setopt($this->handle, CURLOPT_CUSTOMREQUEST, 'DELETE');
-				break;
 			case Requests::HEAD:
+				curl_setopt($this->handle, CURLOPT_CUSTOMREQUEST, $options['type']);
 				curl_setopt($this->handle, CURLOPT_NOBODY, true);
```
Comment (rmccue) [inline library/Requests/Transport/cURL.php]: @egeloen Looks like `CURLOPT_POSTFIELDS` doesn't get set for HEAD requests; was this intentional?
