### PR TITLE
Hooks: priority should be respected

### LINKED ISSUE #452: Hook priority not working
Sorry in advance for my english

I use hook in order to change cURL options
As the bundle add its own hook, I add a priority nomber in order to run mine later.
Unfortunately, it hasn't changed anything.

After looking in the, I found the issue.
In the script of the hook, the priority is used as key for an array of hook.
However, even if the key is a number, the array is not sorted with it.

As solution, I propose to simply use ksort in the register function :
```php
public function register($hook, $callback, $priority = 0) {
	if (!isset($this->hooks[$hook])) {
		$this->hooks[$hook] = array();
	}
	if (!isset($this->hooks[$hook][$priority])) {
		$this->hooks[$hook][$priority] = array();
		ksort($this->hooks[$hook]);
	}
	$this->hooks[$hook][$priority][] = $callback;
}
```

### PR DESCRIPTION
**Pull request by jrfnl**
## Pull Request Type

- [x] I have checked there is no other PR open for the same change.

This is a:
- [x] Bug fix
- [ ] New feature
- [ ] Code quality improvement

## Detailed Description

The `$priority` parameter in the `register()` method is intended to allow for prioritizing the order in which callbacks are run, however, this priority was effectively not used, so callbacks would be run in the order different priorities were _registered_, not ordered _by_ the priorities.

This commit fixes this + adds a unit test to safeguard the fix.

I've elected to add the sorting to the `dispatch()` method, rather than the `register()` method for performance reasons.
Sorting arrays can be expensive and this way, only the subarrays of those hooks which are actually being run will be sorted, instead of sorting the subarray every time a new callback is registered, whether the hook on which the callback is registered will be called or not.

Fixes #452

## Quality assurance

- [x] This change does NOT contain a breaking change (fix or feature that would cause existing functionality to change).
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added unit tests to accompany this PR.
- [x] The (new/existing) tests cover this PR 100%.
- [x] I have (manually) tested this code to the best of my abilities.
- [x] My code follows the style guidelines of this project.

## Documentation

For new features:
- [ ] I have added a code example showing how to use this feature to the [`examples`](https://github.com/WordPress/Requests/tree/develop/examples) directory.
- [ ] I have added documentation about this feature to the [`docs`](https://github.com/WordPress/Requests/tree/develop/docs) directory.
    If the documentation is in a new markdown file, I have added a link to this new file to the Docs folder [`README.md`](https://github.com/WordPress/Requests/tree/develop/docs/README.md) file.

### CODE REVIEW

File: src/Hooks.php [hunk 1]
```diff
@@ -86,6 +86,8 @@ public function dispatch($hook, $parameters = []) {
 			$parameters = array_values($parameters);
 		}
 
+		ksort($this->hooks[$hook]);
```
Comment (schlessera) [inline src/Hooks.php:89]: I don't think this is stable for hooks with the same priority for PHP < 8.0. So, for example for the below tests, hooks `10-1` and `10-2` are not guaranteed to always stay in that same order after `ksort()`, as the behavior for same keys is undefined. From the PHP manual at https://www.php.net/manual/en/function.ksort.php:
> Note:
>
>If two members compare as equal, they retain their original order. Prior to PHP 8.0.0, their relative order in the sorted array was undefined.

Here's how I solved this in a different project: https://github.com/ampproject/amp-toolbox-php/blob/b7377775da193e9cd93fb904421181b47134af70/src/Validator/ValidationErrorCollection.php#L61-L83

I think we'll need something like this here as well, if we want to guarantee that hooks inserted in a certain order for a same priority stay in that same order.

**Review by schlessera — CHANGES_REQUESTED** [review]

File: src/Hooks.php (hunk 1 above)
Comment (jrfnl) [reply src/Hooks.php:89]: The thing is, there never was any mention (documentation) or guarantee that hooks at the _same_ priority would run in a certain order. So yes, while this _may_ change behaviour for callbacks registered on the _same_ priority, the order for those was never fixed anyway.

What this fixes is that the _`$priority`_ parameter - which was the documented way to influence the run order of callbacks, wasn't being respected and now will be.

So if people want to use a specific run order of their callbacks, they should use the (documented) `$priority` parameter and not rely on registration order.

Comment (jrfnl) [reply src/Hooks.php:89]: @schlessera See: https://3v4l.org/gAui9 We're not ordering the callbacks, we're ordering the priorities. That's a different level in the array.

**Review by schlessera — APPROVED** [review]

File: src/Hooks.php (hunk 1 above)
Comment (schlessera) [reply src/Hooks.php:89]: Yes, I understand your point now, and you're right: this is not affected by unstable sorting.
